# Generated by Django 4.2.4 on 2023-09-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
    ]
