# Generated by Django 4.2.4 on 2023-09-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_tasks_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='CreatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
