# Generated by Django 4.2.4 on 2023-09-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_tasks_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='CreatedBy',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='IsDelete',
            field=models.IntegerField(default='0'),
        ),
    ]
